### ISSUE TITLE
lldb-mi failed to locate lldb-server-10.0.0

### ISSUE THREAD

**Issue by Entoryvekum** [lldb-tools/lldb-mi#66] opened 2021-02-06 14:04 UTC
When debugging applications lldb-mi report error “process launch failed: unable to locate lldb-server-10.0.0”.

Environment:
Ubuntu 20.04 LTS on WSL2
LLVM 10.0
Clang 10.0.0
LLDB 10.0.0

![pic](https://user-images.githubusercontent.com/20198566/107139373-9b165200-6955-11eb-91a0-48837c17354b.png)

**Comment by jez** [comment] 2021-02-26 00:51
I'm seeing the same problem. I haven't found a workaround yet.

**Comment by jez** [comment] 2021-02-26 01:28
I was able to work around this by explicitly setting

```
export LLDB_DEBUGSERVER_PATH=/usr/bin/lldb-server-11
```

(for me, the error was "unable to locate lldb-server-11.1.0"—you might want to replace this with wherever you have `lldb-server` on your system, which is probably lldb-server-10 or lldb-server-10.0.0)

I found that by working backwards from where that error is raised in the LLDB source code:

https://github.com/llvm/llvm-project/blob/1fdec59bffc11ae37eb51a1b9869f0696bfd5312/lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunication.cpp#L1212

I don't believe this setting is documented anywhere except in the source code.

Looking at the source code might be a way to find out what the root cause is (presumably lldb-mi should be able to find lldb-server in most cases, so I'm not sure what's holding it back and reading the source might answer that).

**Comment by tkrasnukha** [comment] 2021-10-05 20:43
LLDB uses `dladdr` function to discover the path to liblldb and looks there for lldb-server. However, sometimes this function returns the path to the executable that loaded liblldb (see section BUGS of [the function's man](https://man7.org/linux/man-pages/man3/dladdr.3.html)). Since lldb-server is located in the same directory as lldb executable, it works fine. If you move lldb to another directory, you'll have the same error, I think.

I updated Readme with LLDB_DEBUGSERVER_PATH workaround. Close this issue as it is not an lldb-mi bug.

**Closed** 2021-10-05 20:45 UTC
